export const SET_GAME_IS_PAUSED = "SET_GAME_IS_PAUSED";
export const SPAWN_ENEMY = "SPAWN_ENEMY";
export const SET_CLOSEST_ENEMY = "SET_CLOSEST_ENEMY";
export const PLAYER_TYPED = "PLAYER_TYPED";
export const ENEMY_SHOOT = "ENEMY_SHOOT";
export const UPDATE_HERO_POSITION = "UPDATE_HERO_POSITION";
export const INFLICT_DAMAGE = "INFLICT_DAMAGE";
