name: Undeploy from Firebase (2)

on: workflow_dispatch

jobs:
  undeploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch ${{ github.ref }}
        uses: actions/checkout@v2.3.1
      - name: Undeploy from Firebase
        uses: w9jds/firebase-action@v1.5.0
        with:
          args: hosting:disable -y
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_CI_TOKEN }}
          PROJECT_ID: ${{ secrets.FIREBASE_PROJECT }}
